name: master_brother
description: Master Brother Monitoring App
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.3 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  # Packages
  cupertino_icons: ^1.0.2
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  lottie: ^2.3.2
  iconly: ^1.0.1
  cached_network_image: ^3.2.3
  fl_chart: ^0.62.0
  shared_preferences: ^2.1.1
  firedart: ^0.9.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  #App assets path
  assets:
    - assets/

